/**
 * List of KTU Engineering and Architecture Colleges in Kerala
 * Sourced from KTU_colleges_Kerala_2026.csv
 */

export const KTU_COLLEGES: string[] = [
  "Adi Shankara Institute of Engineering and Technology, Kalady",
  "Ahalia School of Engineering and Technology, Palakkad",
  "Al Azhar College of Engineering and Technology, Idukki",
  "Al-Ameen Engineering College, Palakkad",
  "Albertian Institute of Science and Technology- Technical Campus, School of Engineering, Ernakulam",
  "Amal Jyothi College of Engineering, Kottayam",
  "Archana College of Engineering, Alappuzha",
  "Aryanet Institute of Technology, Palakkad",
  "AWH Engineering College, Kozhikode",
  "Axis College of Engineering and Technology, Thrissur",
  "Baselios Mathews II College of Engineering, Kollam",
  "Baselios Thomas I Catholicose College of Engineering and Technology, Ernakulam",
  "Believers Church Caarmel Engineering College, Ranni",
  "Bishop Jerome Institute, Kollam",
  "Bishop Jerome School of Architecture and Design, Kollam",
  "Carmel College of Engineering and Technology, Alappuzha",
  "Carmel College, Muhamma",
  "CAT College of Architecture, Trivandrum",
  "Christ College of Engineering, Thrissur",
  "Christ Knowledge City, Ernakulam",
  "Cochin Institute of Science and Technology, Ernakulam",
  "College of Engineering and Management, Punnapra",
  "College of Engineering and Technology, Payyanur",
  "College of Engineering, Adoor",
  "College of Engineering, Aranmula",
  "College of Engineering, Attingal",
  "College of Engineering, Chengannur",
  "College of Engineering, Cherthala",
  "College of Engineering, Kallooppara",
  "College of Engineering, Karunagappally",
  "College of Engineering, Kidangoor",
  "College of Engineering, Kottarakkara",
  "College of Engineering, Munnar",
  "College of Engineering, Muttathara",
  "College of Engineering, Pathanapuram",
  "College of Engineering, Perumon",
  "College of Engineering, Poonjar",
  "College of Engineering, Thalassery",
  "College of Engineering, Trikaripur",
  "College of Engineering, Trivandrum",
  "College of Engineering, Vadakara",
  "DC School of Architecture and Design, Thiruvananthapuram",
  "DC School of Management and Technology, Thiruvananthapuram",
  "ER and DCI Institute of Technology, Thiruvananthapuram",
  "Eranad Knowledge City Technical Campus, Malappuram",
  "Federal Institute of Science and Technology, Ernakulam",
  "FISAT Business School, Kochi",
  "Focus Institute of Science and Technology, Poomala",
  "Government College of Engineering, Kannur",
  "Government Engineering College, Barton Hill, Thiruvananthapuram",
  "Government Engineering College, Idukki",
  "Government Engineering College, Kozhikode",
  "Government Engineering College, Sreekrishnapuram",
  "Government Engineering College, Thrissur",
  "Government Engineering College, Wayanad",
  "Government Model Engineering College, Thrikkakara",
  "Gurudeva Institute of Science and Technology, Kottayam",
  "Heera College of Engineering and Technology, Thiruvananthapuram",
  "Hindustan College of Engineering, Kollam",
  "Holy Grace Academy of Engineering, Mala",
  "Holy Kings College of Engineering and Technology, Ernakulam",
  "ICCS College of Engineering and Management, Thrissur",
  "IES College of Engineering, Thrissur",
  "Ilahia College of Engineering and Technology, Muvattupuzha",
  "Ilahia School of Science and Technology, Ernakulam",
  "ILM College of Engineering and Technology, Ernakulam",
  "Indira Gandhi Institute of Engineering and Technology, Ernakulam",
  "Indira Gandhi Institute of Polytechnic and Engineering, Ernakulam",
  "Jai Bharath College of Management and Engineering Technology, Perumbavoor",
  "Jawaharlal College of Engineering and Technology, Palakkad",
  "John Cox Memorial CSI Institute of Technology, Thiruvananthapuram",
  "Jyothi Engineering College, Thrissur",
  "Kerala State Institute of Design, Kollam",
  "KMCT College of Engineering and Management, Kasargod",
  "KMCT College of Engineering For Emerging Technologies and Management, Perinthalmanna",
  "KMCT College of Engineering for Women, Kozhikode",
  "KMCT College of Engineering, Kozhikode",
  "KMCT College of Hotel Management and Catering Technology, Malappuram",
  "KMCT College of Technology and Management, Vadakara",
  "KMCT Institute of Emerging Technology and Management, Kozhikode",
  "KMCT Institute of Engineering and Management, Malappuram",
  "KMCT Institute of Technology and Management, Malappuram",
  "KMEA Engineering College, Ernakulam",
  "KMP College of Engineering, Ernakulam",
  "Kottayam Institute of Technology and Science, Kottayam",
  "KR Gouri Amma College of Engineering, Alappuzha",
  "Kuniya College of Management and IT, Kasaragod",
  "KVM College of Engineering and IT, Alappuzha",
  "LBS College of Engineering, Kasaragod",
  "LBS Institute of Technology for Women, Thiruvananthapuram",
  "Lourdes Matha College of Science and Technology, Thiruvananthapuram",
  "M Dasan Institute of Technology, Kozhikode",
  "Mahaguru Institute of Technology, Mavelikara",
  "Malabar College of Engineering and Technology, Thrissur",
  "Malabar Institute of Technology, Kannur",
  "Mangalam College of Engineering, Kottayam",
  "Mar Athanasius College of Engineering, Kothamangalam",
  "Mar Baselios Christian College of Engineering and Technology, Idukki",
  "Mar Baselios College of Engineering and Technology, Thiruvananthapuram",
  "Mar Baselios Institute of Technology and Science, Ernakulam",
  "Marian Engineering College, Thiruvananthapuram",
  "MEA Engineering College, Malappuram",
  "MES College of Engineering and Technology, Kunnukara",
  "MES College of Engineering, Malappuram",
  "MES Institute of Technology and Management, Kollam",
  "MET's School of Engineering, Thrissur",
  "MG College of Engineering, Thiruvananthapuram",
  "MGM College of Engineering and Technology, Ernakulam",
  "MGM Technological Campus, Malappuram",
  "Mohandas College of Engineering and Technology, Thiruvananthapuram",
  "Mookambika Technical Campus, Ernakulam",
  "Mount Zion College of Engineering, Pathanamthitta",
  "Mount Zion Institute of Management, Kozhuvalloor",
  "Mount Zion Institute of Science and Technology, Alappuzha",
  "Musaliar College of Engineering and Technology, Pathanamthitta",
  "Musaliar College of Engineering, Thiruvananthapuram",
  "Musaliar Institute of Management, Pathanamthitta",
  "Muslim Association College of Engineering, Thiruvananthapuram",
  "Muthoot Institute of Technology and Science, Ernakulam",
  "Nehru College of Engineering and Research Centre, Thrissur",
  "Nirmala College of Engineering, Thrissur",
  "Nirmala College of Management Studies, Chalakkudy",
  "North Malabar Institute of Technology, Kasaragod",
  "NSS College of Engineering, Palakkad",
  "PA Aziz College of Engineering and Technology, Thiruvananthapuram",
  "Pankajakasthuri College of Engineering and Technology, Thiruvananthapuram",
  "Pinnacle School of Engineering and Technology, Anchal",
  "Prime College of Engineering, Palakkad",
  "Providence College of Engineering, Alappuzha",
  "PRS College of Engineering and Technology, Thiruvananthapuram",
  "Rajadhani Business School, Thiruvananthapuram",
  "Rajadhani Institute of Engineering and Technology, Thiruvananthapuram",
  "Rajadhani Institute of Hotel Management and Catering Technology, Thiruvananthapuram",
  "Rajadhani Institute of Science and Technology, Palakkad",
  "Rajagiri School of Engineering and Technology, Kochi",
  "Rajiv Gandhi Institute of Technology, Kottayam",
  "Royal College of Engineering and Technology, Thrissur",
  "Sadguru Swami Nithyananda Institute of Technology, Kasaragod",
  "Sahrdaya College of Engineering and Technology, Thrissur",
  "Saintgits College of Engineering, Kottayam",
  "Saintgits Design School, Kottayam",
  "Saintgits Institute of Computer Applications, Kottayam",
  "Saintgits Institute of Management, Pathamuttom",
  "Sarabhai Institute of Science and Technology, Thiruvananthapuram",
  "SCMS School of Engineering and Technology, Ernakulam",
  "Shahul Hameed Memorial Engineering College, Kollam",
  "SNM Institute of Management and Technology, Ernakulam",
  "South Park Institute of Hotel Management, Thiruvananthapuram",
  "Sree Buddha College of Engineering, Alappuzha",
  "Sree Buddha College of Engineering, Pathanamthitta",
  "Sree Chitra Thirunal College of Engineering, Thiruvananthapuram",
  "Sree Narayana Guru College of Engineering and Technology, Kannur",
  "Sree Narayana Guru Institute of Science and Technology, Ernakulam",
  "Sree Narayana Gurukulam College of Engineering, Ernakulam",
  "Sreepathy Institute of Management and Technology, Palakkad",
  "St Gregorios College of Engineering, Perla",
  "St Joseph's College of Engineering and Technology, Palai",
  "St Thomas College of Engineering and Technology, Alappuzha",
  "St Thomas College of Engineering and Technology, Mattannur",
  "St Thomas Institute for Science and Technology, Thiruvananthapuram",
  "Thejus Engineering College, Thrissur",
  "TKM College of Engineering, Kollam",
  "TKM Institute of Technology, Kollam",
  "Toc H Institute of Science and Technology, Ernakulam",
  "TOMS College of Engineering and Polytechnic, Mattakkara",
  "Travancore Engineering College, Kollam",
  "Trinity College of Engineering, Thiruvananthapuram",
  "UKF College of Engineering and Technology, Kollam",
  "Universal Engineering College, Thrissur",
  "University College of Engineering, Thodupuzha",
  "Valia Koonambaikulathamma College of Engineering and Technology, Trivandrum",
  "Vedavyasa Institute of Technology, Malappuram",
  "Vidya Academy of Science and Technology - Technical Campus, Thiruvananthapuram",
  "Vidya Academy of Science and Technology, Thrissur",
  "Vijnan Institute of Science and Technology, Ernakulam",
  "Vimal Jyothi Engineering College, Kannur",
  "Viswajyothi College of Engineering and Technology, Ernakulam",
  "Younus College of Engineering and Technology, Kollam",
  "Younus College of Engineering, Kollam",
  "Younus Institute of Technology, Kollam"
];

export function searchColleges(query: string, maxResults = 8): string[] {
  if (!query || !query.trim()) return [];
  const q = query.toLowerCase().trim();
  const tokens = q.split(/\s+/);

  return KTU_COLLEGES.filter((college) => {
    const lower = college.toLowerCase();
    return tokens.every((token) => lower.includes(token));
  }).slice(0, maxResults);
}
